# Generated by Django 4.0.4 on 2022-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
